### ISSUE TITLE
'recurse' doesn't work deeper than one directory

### ISSUE THREAD

**Issue by rneatherway** [justone/dfm#33]
Do you think this would be easy to fix?

**Comment by rneatherway** [comment]
Apologies for the noise. I didn't appreciate that .dfminstall config files should be created in subdirectories.

**Comment by justone** [comment]
Ah.  Maybe something for the docs.  Thanks.

**Comment by simonszu** [comment]
Hi,

i am very sorry to dig up this old issue, but it is exactly the problem i have now to import the config-file of the fish shell into dfm. The config file is in ``~/.config/fish/config.fish`` and i am unable to figure out where to put .dfminstall-Files.
I set the .config directory to recurse in the .dfminstall file sitting directly in my ~, but i am unable to get deeper than one directory. Even with a second .dfminstall file in the .config-folder - so please, @rneatherway, how did you manage this issue?

**Comment by rneatherway** [comment]
I have a very similar configuration, so my root `.dfminstall` contains `.config recurse` and then `.config/.dfminstall` contains `xfce4 recurse`. It works fine for me, so I'm not sure what the problem is at your end.
