### ISSUE TITLE
Importing a folder nested inside another one (.vim/Ultisnips without the whole .vim)

### ISSUE THREAD

**Issue by netei** [justone/dfm#34]
Hi,

When I run `dfm import ~/.vim/UltiSnips`, I get the following error : 

`ERROR: file .vim/UltiSnips is in a subdirectory that is not tracked, consider using 'dfm import .vim'.`

I would like to include `.vim/UltiSnips` into my dotfiles, but without including my full `.vim` folder. Is this somehow possible ?

I don't wish to import my full `.vim` directory inside my dotfiles, because it contains a lot of things that aren't interesting to me (all versions of all bundles)

**Comment by justone** [comment]
Hey,

In your situation, you can use dfm's recursion capabilities.  The following should get you set up:

```
$ cd ~
$ echo ".vim recurse" >> .dotfiles/.dfminstall
$ mkdir .dotfiles/.vim
$ mv .vim/UltiSnips .dotfiles/.vim
$ dfm add .dfminstall .vim
$ dfm commit -m "adding ultisnips"
```

After doing this, you can do `dfm import .vim/otherplugin` and dfm will do the right thing.  It's just the initial set up that's a little complicated.  Perhaps I can teach `dfm import` to do this set up in the future.

**Comment by netei** [comment]
Ok, works fine. Thanks a lot !

**Comment by netei** [comment]
It would be great that it would work automatically with `dfm import` as you said.

**Comment by edi9999** [comment]
Hi, same person here (netei). I have had some problems when I did `dfm install from an other machine, my complete .vim/bundle was deleted. I think it is not expected behaviour.

**Comment by justone** [comment]
Hey,

That is definitely unexpected.  `dfm install` shouldn't ever delete files.  When it is installing and finds a directory where it wants to put something it will move it to `$HOME/.backup`.  Do you have that directory and are your files in there?

Sorry for the inconvenience.

**Comment by edi9999** [comment]
Strangely I have two directories with ".backup"  : 

`~/.vim/.backup` which is empty

`~/.backup` but it doesn't contain a `.vim` folder.

**Comment by justone** [comment]
That's odd.  Could you share your dotfiles repo with me so I can try to replicate it?  Or, if you'd rather not do that, can you create a dotfiles repo and set of steps to reproduce the bug?

Thanks for your help.

**Comment by edi9999** [comment]
Hi, yes here's the link to the repository : (I've made it public)

git clone https://bitbucket.org/edi9999/dotfiles.git

**Comment by edi9999** [comment]
For information, I've run dfm install from my home directory.

**Comment by justone** [comment]
Thanks for the information.  I'll try to get to it this weekend.

**Comment by edi9999** [comment]
Hi, any updates on this ?

**Comment by justone** [comment]
Hey, sorry for the delay, life got busy for a bit. I have some travel time on a plane this week, so I'll try to get to it.

**Comment by justone** [comment]
Hey,  I tried installing your dotfiles on a test machine.  I made a local .vim/bundle directory with a plugin inside and then installed your dotfiles.  In my test, the .vim/bundle directory is still there after installation.

What sequence of commands are you running where the bundle directory gets deleted?

Thanks.

```
nate@testmachine:~$ mkdir -p .vim/bundle/
nate@testmachine:~$ cd .vim/bundle/
nate@testmachine:~/.vim/bundle$ git clone https://github.com/tpope/vim-fugitive.git
Cloning into 'vim-fugitive'...
remote: Counting objects: 2099, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 2099 (delta 4), reused 0 (delta 0), pack-reused 2087
Receiving objects: 100% (2099/2099), 755.91 KiB | 1.29 MiB/s, done.
Resolving deltas: 100% (767/767), done.
Checking connectivity... done.
nate@testmachine:~/.vim/bundle$ cd ~
nate@testmachine:~$ git clone https://bitbucket.org/edi9999/dotfiles.git .dotfiles
Cloning into '.dotfiles'...
remote: Counting objects: 2026, done.
remote: Compressing objects: 100% (1130/1130), done.
remote: Total 2026 (delta 1227), reused 1365 (delta 809)
Receiving objects: 100% (2026/2026), 303.65 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1227/1227), done.
Checking connectivity... done.
nate@testmachine:~$ ./.dotfiles/bin/dfm install
INFO: Installing dotfiles...
INFO:   Symlinking .fzf.bash (.dotfiles/.fzf.bash).
INFO:   Symlinking .git_template (.dotfiles/.git_template).
INFO:   Symlinking .gitconfig (.dotfiles/.gitconfig).
INFO:   Symlinking .tmux.conf (.dotfiles/.tmux.conf).
INFO:   Symlinking .profile (.dotfiles/.profile).
INFO:   Symlinking .ctags (.dotfiles/.ctags).
INFO:   Symlinking bin (.dotfiles/bin).
INFO:   Symlinking .shellrc.load (.dotfiles/.shellrc.load).
INFO:   Symlinking .bashrc (.dotfiles/.bashrc).
INFO:   Symlinking .vimrc (.dotfiles/.vimrc).
INFO:   Symlinking .edgarstart (.dotfiles/.edgarstart).
INFO:   Symlinking scripts (.dotfiles/scripts).
INFO:   Symlinking .fzf-key-bindings.bash (.dotfiles/.fzf-key-bindings.bash).
INFO:   Symlinking windows (.dotfiles/windows).
INFO:   Symlinking .tigrc (.dotfiles/.tigrc).
INFO:   Symlinking UltiSnips (../.dotfiles/.vim/UltiSnips).
INFO:   Symlinking after (../.dotfiles/.vim/after).
nate@testmachine:~$ ls -l .vim
total 4
lrwxrwxrwx 1 nate nate   23 Oct  6 11:54 after -> ../.dotfiles/.vim/after
drwxrwxr-x 3 nate nate 4096 Oct  6 11:53 bundle
lrwxrwxrwx 1 nate nate   27 Oct  6 11:54 UltiSnips -> ../.dotfiles/.vim/UltiSnips
nate@testmachine:~$ ls -l .vim/bundle/
total 4
drwxrwxr-x 5 nate nate 4096 Oct  6 11:53 vim-fugitive
nate@testmachine:~$ 
```

**Comment by edi9999** [comment]
I can't reproduce the issue on a new machine either. I will tell you if this happens again in the future and try to create a script to reproduce the issue in that case

**Comment by justone** [comment]
Sounds good. Thank you.
